"""
Author: Ben Janis
Date: 2025

This source file is part of an example system for MITRE's 2025 Embedded System CTF
(eCTF). This code is being provided only for educational purposes for the 2025 MITRE
eCTF competition, and may not meet MITRE standards for quality. Use this code at your
own risk!

Copyright: Copyright (c) 2025 The MITRE Corporation
"""

import argparse
import struct
import json
import hashlib
import os
from cryptography.hazmat.primitives.ciphers.aead import ChaCha20Poly1305
from secrets import token_bytes
import ectf25_design
import ectf25_design.encoder

TOTAL_FRAMES = 3

def encryptFrame(fNum, root_key, frame_data, channel_num):
    frameKey = calcKey(root_key, fNum)
    if channel_num == 0:
        frameKey = root_key

    nonce = token_bytes(12)
    
    ad = b''
    ad += struct.pack('<IQ', channel_num, fNum)
    ad += nonce

    # since this is a stream cipher, we must pad the plaintext to 64 bytes
    assert len(frame_data) <= 64 # guaranteed by spec
    length = len(frame_data)
    frame_data += b'\00' * (64 - len(frame_data))
    frame_data = length.to_bytes(1, byteorder='big') + frame_data

    cipher = ChaCha20Poly1305(frameKey)
    ciphertext_and_tag = cipher.encrypt(nonce, frame_data, ad)

    ciphertext, tag = ciphertext_and_tag[:-16], ciphertext_and_tag[-16:]

    return ciphertext, nonce, tag, ad, frameKey

def calcKey(root_key: bytes, frame: int) -> bytes:
    key, level = root_key, 64

    # the range of frames the current key covers
    covered_start, covered_end = 0, 2**64 - 1

    while True:
        if level <= 0:
            break

        if covered_start == frame and covered_end == frame:
            break

        child_level = level - 1
        child_start = (frame >> child_level) << child_level # salt

        key, level = ectf25_design.encoder.hash(key, child_start), child_level
        covered_start, covered_end = child_start, child_start + (1 << level) - 1

    return key

def hash(currKey, fNum):
    hash_result = hashlib.sha256(currKey + struct.pack('<Q', fNum)).digest()
    return hash_result

class Encoder:
    def __init__(self, secrets: bytes):
        """
        You **may not** change the arguments or returns of this function!

        :param secrets: Contents of the secrets file generated by
            ectf25_design.gen_secrets
        """

        # Load the json of the secrets file
        secrets = json.loads(secrets)
        self.root_keys = secrets['root_keys']

    def encode(self, channel: int, frame: bytes, timestamp: int) -> bytes:
        """The frame encoder function

        This will be called for every frame that needs to be encoded before being
        transmitted by the satellite to all listening TVs

        You **may not** change the arguments or returns of this function!

        :param channel: 16b unsigned channel number. Channel 0 is the emergency
            broadcast that must be decodable by all channels.
        :param frame: Frame to encode. Max frame size is 64 bytes.
        :param timestamp: 64b timestamp to use for encoding. **NOTE**: This value may
            have no relation to the current timestamp, so you should not compare it
            against the current time. The timestamp is guaranteed to strictly
            monotonically increase (always go up) with subsequent calls to encode

        :returns: The encoded frame, which will be sent to the Decoder
        """

        key = None
        for key_obj in self.root_keys:
            if (key_obj['channel_num'] == channel):
                key = key_obj['root_key']
                break
        if key == None:
            raise Exception(f'No key defined for channel {channel}')
        
        ciphertext, nonce, tag, ad, frameKey = encryptFrame(timestamp, bytes.fromhex(key), frame, channel)
        return struct.pack('<IQ', channel, timestamp) + nonce + ciphertext + tag

def main():
    """A test main to one-shot encode a frame

    This function is only for your convenience and will not be used in the final design.

    After pip-installing, you should be able to call this with:
        python3 -m ectf25_design.encoder path/to/test.secrets 1 "frame to encode" 100
    """
    parser = argparse.ArgumentParser(prog="ectf25_design.encoder")
    parser.add_argument(
        "secrets_file", type=argparse.FileType("rb"), help="Path to the secrets file"
    )
    parser.add_argument("channel", type=int, help="Channel to encode for")
    parser.add_argument("frame", help="Contents of the frame")
    parser.add_argument("timestamp", type=int, help="64b timestamp to use")
    args = parser.parse_args()

    encoder = Encoder(args.secrets_file.read())
    print(repr(encoder.encode(args.channel, args.frame.encode(), args.timestamp)))


if __name__ == "__main__":
    main()
